---
- name: Create Namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: open-cluster-management

- name: Create OperatorGroup
  kubernetes.core.k8s:
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    state: present
    definition:
      apiVersion: operators.coreos.com/v1
      kind: OperatorGroup
      metadata:
        name: open-cluster-management-group
        namespace: open-cluster-management
      spec:
        targetNamespaces:
          - open-cluster-management
          
- name: Create Operator Subscription
  kubernetes.core.k8s:
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    state: present
    template: operator.yml
    wait: true
    wait_condition:
      type: 'CatalogSourcesUnhealthy'
      reason: 'AllCatalogSourcesHealthy'
      status: 'False'

- name: Wait for MultiClusterHub (MCH) CRD
  kubernetes.core.k8s_info:
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    kind: CustomResourceDefinition
    name: multiclusterhubs.operator.open-cluster-management.io
    wait: true
    wait_condition:
      type: 'Established'
      reason: 'InitialNamesAccepted'
      status: 'True'
    wait_timeout: 300

- name: Setup MultiClusterHub (MCH) instance
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ ocm_hub_kubeconfig }}"
    template: multiclusterhub.yml
    wait: true
    wait_condition:
      type: 'Complete'
      reason: 'ComponentsAvailable'
      status: 'True'
    wait_timeout: 600
